### ISSUE TITLE
Gustavo's ToDo List

### ISSUE THREAD

**Issue by gburin** [gvdr/2016_Forward_Simulation#2]
- [ ] Improve the evolving functions
- [ ] make sure the inheriting functions are ok
- [ ] improve the get adjacency function, and add plotting options
